settings:
  web:
    label: "Weboberfläche"
  camera:
    label: "Kamera"
  remote_access:
    label: "Fernzugriff"
  snapmaker_components:
    label: "Snapmaker-Komponenten"
  print_preferences:
    label: "Druckverhalten"
  tweaks:
    label: "Feineinstellungen"
  troubleshooting:
    label: "Fehlersuche"
  monitoring_debugging:
    label: "Überwachung und Fehlersuche"
